### ISSUE TITLE
Presets not updating in the editor

### ISSUE THREAD

**Issue by stupinkney** [weDevsOfficial/happy-elementor-addons#13]
Hi there,

I've just started using Happy Addons Pro, but have immediately encountered an issue with the widget presets.

I thought that selecting a new preset (e.g. Preset 3) would automatically show that preset design in the editor window, but that's not happening. Instead, the default design continues to show until I hit Publish and then refresh the page.

Do you know how I can fix this?

Thanks, Stu.

**Comment by Gelouis** [comment]
Same problem here and more, can't copy any live templates in my website. Any clues?

**Comment by thebengalboy** [comment]
Hello @stupinkney @Gelouis 

We are already concerned about this. Actually, Elementor changed its core JS API in version 2.8.0 which we used to implement cross copy, live copy and presets. Elementor changed their API without backward compatibility that's why we are facing such a situation and our dev team is working diligently to resolve the issue and find a long-lasting solution.

Thanks

**Comment by sw0rking** [comment]
1.3.0

Release Date – Dec 31, 2019

    New: Promo Box widget
    New: CSS Image Masking (Supported widgets: Card, Info Box, Promo Box, Member, Image, Image Box)
    Update: Cross-Domain Copy Paste UX improved
    Update: Cross-Domain Copy Paste performance improved
    Update: Live Copy Paste UX improved
    Update: Live Copy Paste performance improved
    Update: Context menu items are moved to an upper position
    Fix: Unlimited Section Nesting compatibility issue with Elementor

**Comment by obiPlabon** [comment]
Fixed
