### ISSUE TITLE
Happy add-ons CSS conflict with Premium Elementor add-ons

### ISSUE THREAD

**Issue by WpEmbraced** [weDevsOfficial/happy-elementor-addons#26]
There are CSS lines being applied globally and they are having a conflict with carousel navigation dots list in Premium Elementor add-ons. Is there a way to prevent this so both plugins can play nicely with each other?

Here's a screenshot: https://cl.ly/57060ee59f46

The conflict stops the Premium Elementor add-on's Hotspot/carousel from working.

Thanks

**Comment by obiPlabon** [comment]
@WpEmbraced You are right there are some CSS styles that are being applied globally. And an interesting fact is those styles basically default Slick slider styles and comes with Slick slider. Premium addons overwrote those default styles and that's why there's the conflict.

No worries we'll find a better way to handle such situations, and for that, we need a good amount of time.

Thanks
