### ISSUE TITLE
Dokan compatibility

### ISSUE THREAD

**Issue by steveavador** [weDevsOfficial/happy-elementor-addons#67]
Hello I have the free version of dokan and happy addons installed in my site. I noticed that happy addons is causing that in dokan vendors can't upload images for their products or even change the logo and the banner. I think that this issue comes from this plugin because I deactivate all the other plugins except dokan, happy addons and woocommerce of course.

**Comment by obiPlabon** [comment]
Hello @steveavador did you try deactivating HappyAddons? Could you please try that and let us know?

Thanks

**Comment by mmarj** [comment]
Hello @steveavador 
I found it's working with the latest version of HappyAddons and Dokan. Please check [out this quick video](https://drive.google.com/file/u/3/d/1SL0oe31QIt5kQJ1em2KGzOwZ4P5nsD-R/view?usp=sharing). 

If you are still facing the same, then would you please contact our support from (support@wedevs.com) by sharing your site access so that we can have a closer look at your backend environment and assist you further.

Regards.
