### ISSUE TITLE
Happy Addons PRO Plugin affecting Elementor Forms

### ISSUE THREAD

**Issue by joaonew** [weDevsOfficial/happy-elementor-addons#68]
**Describe the bug**
Since the last version came out I noticed that the forms in my website were missing 4 of its 7 inputs. Tried deactivating all plugins, but only when I deactivated Happy Addons Pro Plugin that it fixed the form.

**To Reproduce**
1. Go to your plugins
2. Deactivate/Activate Happy Addons Pro Plugin
3. See behavior on forms

**Screenshots**
This is the form with the Plugin Deactivated:
![image](https://user-images.githubusercontent.com/43939710/95489079-5c02d080-0964-11eb-9de9-96dece6f9511.png)

And this is the same form with the Plugin Activated:
![image](https://user-images.githubusercontent.com/43939710/95489124-6fae3700-0964-11eb-8446-1320652df0af.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Browser chrome
 - Elementor Version 3.0.11
 - Elementor Pro Version 3.0.5
 - HappyAddons Version 2.14.2
 - HappyAddons Pro version 1.10.0

Already opened a ticket but figured to send it here also so maybe can get a fix faster

**Comment by joaonew** [comment]
19 days and no fix, clear answer on if I should renew my license or not by now

**Comment by obiPlabon** [comment]
Hi @joaonew 

We are really sorry for the inconvenience and delay. We couldn't resolve the issue but figured out an alternative solution! You can simply disable the Display Condition feature and the form will work as expected or as it was before. Just copy the following line of code and paste it into your theme's `functions.php`

```php
add_filter( 'happyaddons/extensions/display_condition', '__return_false' );
```

And regarding the delay, I believe we owe you an explanation. So here it is - in the 3.x.x update Elementor made some changes in the Repeater field, which we are using for Display Condition. And due to the changes, 2 repeater fields in the form widget are conflicting with each other! There were more bugs related to the repeater field which Elementor fixed over time with patch releases. So we were waiting for their feedback on this issue since we cannot make any changes in the Elementor core. So the only solution we have now is to disable the display condition. And we added this hook on the 22 October update only after getting your report.

Yeah, we should have informed you of this situation before and we are really sorry for the inconvenience.

Thank you :)

**Comment by joaonew** [comment]
Thank you for the explanation. I will try to configure the functions.php although I never did it before.
I would like to hear something about getting a refund for the whole month that I was not able to turn on the Happy Addons Pro plugin...

**Comment by Goaff** [comment]
I have a very similare issue. HA pro activated = 307 redirection on loop when trying to send a form.
the snippet to add in functions.php has no effect on my side.

Any idea?

**Comment by ronald-edge** [comment]
This bug has reappeared. 

- OS : Windows 10 Pro Version 2004
- WordPress : version: 5.7
- Browser : Chrome + Firefox
- Elementor : Version 3.1.4
- Elementor Pro : Version 3.1.1
- Happy Elementor Addons : Version 2.21.1
- Happy Elementor Addons Pro :  Version 2.21.1

I was able to resolve the issue by disabling the "Display Conditions" feature via the Happy Addons panel in WordPress:
HappyAddons > Features > Display Condition (toggle: off)

**Comment by nicmare** [comment]
same problem here!
