### ISSUE TITLE
Grid Layout does not display

### ISSUE THREAD

**Issue by swboucher** [weDevsOfficial/happy-elementor-addons#69]
The Grid Layout widget does not display on a website with similar plugins to another working website. The non-functioning website uses the Astra Pro theme. The functioning website uses the GeneratePress Pro theme. Before I start disabling plugins and changing themes, do you have troubleshooting suggestions or known conflicts? The Grid Layout widget settings are default. I have checked open and closed tickets and HappyAddons support but can't find a solution.

**Comment by obiPlabon** [comment]
Hello @swboucher, sorry for the delay.

Grid Layout is not a widget actually, it's a feature, and here's the details page https://happyaddons.com/happy-grid-layout-demo/

And you can find it here.
![image](https://user-images.githubusercontent.com/10244644/97398359-4ec46c00-18a8-11eb-89fc-e9f8395372a6.png)

I guess due to term mismatch it's a bit difficult to find, we'll match the term in the next update.

Thanks
