### ISSUE TITLE
Disable Cookie HappyLocalTimeZone

### ISSUE THREAD

**Issue by Chris-0816** [weDevsOfficial/happy-elementor-addons#84]
HappyAddons Pro automatically set the Cookie  "HappyLocalTimeZone" for the "display conditions" feature. 
On most websites I haven't display conditions feature in use. 
Because of the EU Cookie law  I always have to explain what cookies are set and used for. 
I now have to create a cookie consent banner especially for the "HappyLocalTimeZone" cookie because I have no other cookies in use.

It would be great if the happyAddons features could be turned on and off from the dashboard like the normal widget.
Most AddonPuplisher like UEA, Essential Addons,.. have this option.

![toggle](https://user-images.githubusercontent.com/75832963/101893582-39c84180-3ba5-11eb-9191-f3756899a2b3.PNG)

**Comment by stuartbrameld** [comment]
agreed, same issue for me

**Comment by sayedulsayem** [comment]
@Chris-0816 and @stuartbrameld 
This issue is solved and will be included in our next release. This cookie won't be set if you don't use the display condition feature on a page.

There is an option to turn off display conditions. [See here](https://prnt.sc/26cqh8t)

### Explanation of this cookie used for:

This cookie is used for display conditions. It set visitors' local time on the cookie.

**Comment by Chris-0816** [comment]
thanks a lot, good to know!
